parameters:
#    gladtur_tag.example.class: Gladtur\TagBundle\Example

services:
#    gladtur_tag.example:
#        class: %gladtur_tag.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
