imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      #assets_version: SomeVersionScheme
      engines: ['twig']
      form:
        resources:
          - 'TagBundle:Form'
    default_locale:  %locale%
    trust_proxy_headers: false # Should Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
      resources:
        - 'GladturTagBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        filters:
          softdeleteable:
            class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
            enabled: true

# Swiftmailer Configuration
swiftmailer:
  transport:  smtp
#  encryption: ssl
#  auth_mode:  login
  host:       127.0.0.1
#  username:   mortenthorpe@gmail.com
#  password:   @tS0mmerhus

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Gladtur\TagBundle\Entity\User

services:
    acme_hello.twig.extension.debug:
        class:        Twig_Extension_Debug
        tags:
             - { name: 'twig.extension' }

    GladturTagBundle.image_type_extension:
        class: Gladtur\TagBundle\Form\Type\ImageTypeExtension
        tags:
            - { name: form.type_extension, alias: file }

    oauth_event_listener:
        class:  Gladtur\MobileBundle\Event\oAuthPreAuthListener
        tags:
          - { name: kernel.event_listener, event: fos_oauth_server.pre_authorization_process, method: onPreAuthorizationProcess, arguments: @service_container }
    mobile_useragent_listener:
        class: Gladtur\MobileBundle\Event\UserAgentListener
        arguments: ["%useragents%"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelControllerPermission }
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelControllerReceiveJSON }

    gedmo.listener.softdeleteable:
        class: Gedmo\SoftDeleteable\SoftDeleteableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]

#fos_oauth_server:
#    db_driver: orm       # Driver availables: orm, mongodb, or propel
#    client_class:        Gladtur\TagBundle\Entity\Client
#    access_token_class:  Gladtur\TagBundle\Entity\AccessToken
#    refresh_token_class: Gladtur\TagBundle\Entity\RefreshToken
#    auth_code_class:     Gladtur\TagBundle\Entity\AuthCode
#    service:
#      user_provider: fos_user.user_manager

#fos_rest:
#    routing_loader:
#        default_format: json
#    format_listener:
#        default_priorities: [html, json, '*/*']

# See http://symfony.com/doc/2.1/cookbook/event_dispatcher/before_after_filters.html, also for token example!
parameters:
  useragents:
    ios: "Gladtur - iOS"
    android: "Gladtur - Android"

#hwi_oauth:
# name of the firewall in which this bundle is active, this setting MUST be set
#  firewall_name: secured_area
stof_doctrine_extensions:
  default_locale: en_US
  orm:
    default:
      timestampable: true


