# app/config/security.yml
security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                always_use_default_target_path: false
                default_target_path: /

            logout:       true
            anonymous:    true
#        ajax_login:
#            pattern: ^/
            ajax_form_login:
              provider: fos_userbundle
              #csrf_provider: form.csrf_provider
              always_use_default_target_path: false
              use_referer: true
              default_target_path: /


    access_control:
        - { path: ^/admin.*?$, role: ROLE_ADMIN }
        - { path: ^/admin/.*?$, role: ROLE_ADMIN }
        - { path: ^/test\/?$, role: ROLE_TVGUSER }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:
        ROLE_TVGUSER:     [ROLE_USER, ROLE_TVGUSER]
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_SUPER_ADMIN: ROLE_ADMIN
